config/routes.rb
Rails.application.routes.draw do


  resources :posts do
    resources :comments, shallow: true, only: [:create, :destroy] 
  end

  get '/follow/:id', to: 'users#follow', as: 'follow_user'
  get '/unfollow/:id', to: 'users#unfollow', as: 'unfollow_user'
  #post '/posts/:id', to: 'posts#show'
  # commented out because of resources :posts
  # get 'posts/index'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/show'
  # get 'posts/destroy'
  # get 'posts/index'
  # get 'posts/new'
  # get 'posts/create'
  # get 'posts/show'
  # get 'posts/destroy'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  
  resources :users

  # commented out because resourses :users
  # get 'users/index'
  # get 'users/new'
  # get 'users/show'
  # get 'users/edit'

  
  
  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates_uniqueness_of :follower_id, scope: :followed_id
  validates_uniqueness_of :followed_id, scope: :follower_id
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :active_relationships, class_name: "Relationship",
	                          foreign_key: :follower_id, 
	                          dependent: :destroy
  	has_many :passive_relationships, class_name: "Relationship",
	                           foreign_key: :followed_id, 
	                           dependent: :destroy
  	has_many :following, through: :active_relationships,  source: :followed # User.first.following
  	has_many :followers, through: :passive_relationships, source: :follower # User.first.followers
	has_many :comments
	validates_uniqueness_of :email
	validates :email, confirmation: true
	validates_presence_of :fname, :lname, :email, :email_confirmation, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  def create
  	@comment = Comment.create(params.require(:comment).permit(:body).merge(user: current_user, post_id: params[:post_id]))
  	redirect_to @comment.post
  end

  def show
  	@comment = Comment.all
  end

  def destroy
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @posts = Post.all
  end

  def new
    if current_user
      @post = Post.new
    else
      flash[:notice]= "Please sign in order to post"
      redirect_to login_path
    end
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      flash[:notice] = "New post created"
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def update
  
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post was deleted"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body).merge(user: current_user)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user and @user.password == params[:password]
  		session[:user_id] = @user.id
  		flash[:notice] = 'You\'ve logged in'
  		redirect_to posts_path
  	else
  		flash[:alert] = 'Incorrect password or email'
  		render :new
  	end
  end

  def delete
  	session[:user_id] = nil
  	flash[:notice] = "Logged out"
  	redirect_to root_path
  end  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]
	#a security feature RoR forms require, only allows a user to create or update only the attribures whitelisted.
  
  def index
  	@user = User.all
  end

  def new
  	@user = User.new
  end

  def show
  	set_user 
  end

  def follow
    @relationship = Relationship.new(follower_id: current_user.id, followed_id: params[:id])
    @user = User.find(params[:id])
    if @relationship.save
      flash[:notice] = "You've successfully followed #{@user.fname}."
    else
      flash[:alert] = "There was an error following that user."
    end
      redirect_to users_path(@user.username) #username_path(@user.username)
  end

  def unfollow
    @relationship = Relationship.find_by(follower_id: current_user.id, followed_id: params[:id])
    @user = User.find(params[:id])
    if @relationship and @relationship.destroy
      flash[:notice] = "You've successfully unfollowed #{@user.fname}"
    else
      flash[:notice] = "There was an error unfollowing that user"
    end
    redirect_to posts_path
  end

  def edit
  	 set_user  #<-- before_action command replaces this set_user
  end

  def create
  	# set_user <-- before_action command replaces this set_user
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = 'New account created'
  		redirect_to user_path(@user)
  	else
  		flash[:alert] = 'There was a problem'
  		render :new
  	end
end

  def update
     set_user  #before_action command replaces this set_user
    @user.update(user_params)
    flash[:notice] = "Your account was updated"
    redirect_to user_path(@user) # can also be just @user RoR knows its a shortcut
  end


  def destroy
  	set_user  #  before_action command replaces this set_user
  	@user.destroy
    session[:user_id] = nil
  	flash[:notice] = "User was deleted"
    redirect_to users_path
  end

private

  def set_user
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:fname, :lname, :email, :email_confirmation, :password) #this is a vey specific syntax, MEMORIZE it a.s.a.p.
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iread</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

	<nav>
		<ul>
		<% if current_user %>

		<li id="name"><%= "Hi #{current_user.fname}! " %></li>
		<li><%=link_to('Edit Profile', edit_user_path(current_user.id), method: :get) %></li></br>
		<li><%= link_to( 'Sign out', logout_path, method: :delete) %></li></br>
		<li><%= link_to 'Create new Post', new_post_path %></li></br>
        <li><%= link_to 'View all posts', posts_path %></li>                
		<% else %>    
	       
		<%= form_tag('/login', method: :post) do |f| %>
        <li><%= link_to " Sign up", new_user_path %></li>
        <li><%= submit_tag :Login %></li>
        <li><%= password_field_tag(:password,"", placeholder: 'Password') %></li>             
		<li><%= email_field_tag(:email,"", placeholder: 'Email')  %></li>
		
		
		<% end %>
		<% end %>
        </ul>                
	</nav>

<body>
	<main>

		<%= flash[:notice] if flash[:notice] %>
        <%= flash[:alert] if flash[:alert] %>

		<%= yield %>

	</main>
</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<!-- Posts#index -->
<!-- Find me in app/views/posts/index.html.erb -->
<main id="body">
<div id="showindex">
	<p>All Posts</p>
	<% @posts.each do |p| %>
	<ul>
		<li><%=	link_to p.body, post_path(p.id) %> | <%= p.user.fname %></li> 
	</ul>
	<% end %>
<button><%= link_to 'Create new Post', new_post_path %></button>

</div>


 
	
</main>

    

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<% if current_user %> 
	<h5>Post a post below</h5>
	<%= form_for [@post] do |f| %>
		<%= f.text_area :body %><br>
		<%= f.submit %>
	<% end %>
<% else %>
	<h5><%= link_to 'Login', login_path %> to comment!</h5>
<% end%>

<% @post.comments.each do |comment| %>
	<p><%= comment.body %> (<%= comment.user.name %>)</p>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>

<% if @post.errors.any? %>
	<% @post.errors.full_message.each do |error| %>
	<p style="color: red bold;"><% error %></p>
	<% end%>
<% end %>

<div id="postshow">
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<p>Click <%= link_to 'here', edit_post_path %> to edit your post</p>
<p> Click <%= link_to 'here', post_path(@post.id), method: :delete %> to delete your post</p>
<hr>
<% @post.comments.each do |comment| %>
	<p><%= comment.body %> (<%= comment.user.fname %>)</p>
<%end %>
</body>
<hr>




<% if current_user %> 
	<h5>Post a comment below</h5>
	<%= form_for [@post, @comment] do |f| %>
		<%= f.text_area :body %><br>
		<%= f.submit %>
	<% end %>
<% else %>
	<h5><%= link_to 'Login', login_path %> to comment!</h5>
<% end%>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
		<% @user.errors.full_messages.each do |error| %>
			<p style="color: red;"><%= error %></p>
		<% end %>
	<% end %>

<%= form_for @user do |f| %>

	<p>
		<%= f.text_field :fname, placeholder: 'First Name' %>
	</p>
	<p>
		<%= f.text_field :lname, placeholder: 'Last Name' %>
	</p>
	<p>
		<%= f.email_field :email, placeholder: 'Email' %>
	</p>
	<p>
		<%= f.email_field :email_confirmation, placeholder: 'Confirm email' %>
	</p>
	<p>
		<%= f.password_field :password, placeholder: 'Password' %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

<div id="edit">
<%= "#{current_user.fname}'s Profile Page" %>

<%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div id='join'>
	<h2>Join the Book Club!</h2>

	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>

<%= @user.fname %>
<% if current_user and current_user == @user %>
<p><%= link_to 'delete user', user_path(@user.id), method: :delete %></p>
<p><%= link_to 'Edit', edit_user_path(@user.id) %></p>
<%=link_to "Delete", user_path(user_id: @user.id), method: :delete, remote: true, class: "delete-user" %>
<% end %>

<% if current_user != @user %>
	<%if current_user and current_user.following.include?(@user) %>
<p><%= link_to 'unfollow', unfollow_user_path(@user), remote: true %></p>
	<% else %>
	<p><%= link_to 'follow', follow_user_path(@user), remote: true %></p>
<% end %>
<% end %>


<p>Following<%= @user.following.length %> user's</p>
<p>Followed by <%= @user.followers.length %> user's</p>

app/views/welcome/index.html.erb
<h1>iRead Landing page</h1>